application: foipenalti
version: 5
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
  expiration: 10d 

- url: /img
  static_dir: img
  expiration: 10d 

- url: /js
  static_dir: js
  expiration: 10d 

- url: /static
  static_dir: static
  expiration: 10d 

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 10d 

- url: /apple-touch-icon.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png
  expiration: 10d 

- url: /apple-touch-icon-precomposed.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png
  expiration: 10d 

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: 10d 

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /admin/.*
  script: boot.py
  login: admin

- url: /task/.*
  script: boot.py
  login: admin

- url: /cron/.*
  script: boot.py
  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /.*
  script: boot.py

# pre-compile all Pythons
derived_file_type:
- python_precompiled

admin_console:
  pages:
  - name: Criar posta blog
    url: /admin/post/create


builtins:
- datastore_admin: on
#- appstats: on
